### PR TITLE
Added Swagger UI Client Code Snippets

### PR DESCRIPTION
**Pull request by codestellar**
Added a plugin to show client side code snippets in Swagger UI
image

### CODE REVIEW

**Comment by emonney** [comment]
swaggerui-snippets.bundle.js is a bundled file. The source is necessary for debugging/support/maintenance

**Comment by codestellar** [comment]
@emonney Do you want me to add this in dotnet build pipeline? Generating the minified file is not required each time. As the swagger UI is not going to change, This is just another plugin to extend swagger UI.
I can still add code if you want.
[https://www.npmjs.com/package/swaggerui-snippets](https://www.npmjs.com/package/swaggerui-snippets)

**Comment by balapkm** [comment]
Can you please example for JS

**Comment by codestellar** [comment]
@balapkm Help me understand what are you looking for?

**Comment by dsoltesz** [comment]
this request doesn't work as it give a 404 for finding the bundle.  Also you have a dependency on swagger-snippet...this package has been renamed to openapi-snippet as well.  Please update the PR so it works with the latest code

**Pull request closed without merging**
